name: app
description: PicTalk Animals 

version: 1.0.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  get_it: ^7.7.0
  easy_localization: ^3.0.7
  go_router: ^14.2.0

  dio: ^5.4.3+1
  jwt_decode: ^0.3.1
  connectivity_plus: ^6.0.3
  hive: ^2.2.3
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1 
  modal_bottom_sheet: ^3.0.0
  google_fonts: ^6.2.1
  file: ^7.0.0
  flutter_portal: ^1.1.4
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0
  gap: ^3.0.1 
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  blurhash: ^1.1.1
  flutter_switch: ^0.3.2
  flutter_tts: ^4.0.2
  
  device_info_plus: ^10.1.0
  client_information: ^2.1.4
  dart_ipify: ^1.1.1
  package_info_plus: ^8.0.0
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  webview_flutter: ^4.8.0

  internal_core: 
    path: internal_libs/core

dependency_overrides:
  http: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  #ios
  image_path: "assets/logo.png"
  #android 
  adaptive_icon_foreground: "assets/logo2.png"
  adaptive_icon_background: "#ffffff"
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo2.png
  web: false
  

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true


flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/jsons/
    - assets/images/svg/ 
    - assets/images/animals/ 
