import 'package:internal_core/internal_core.dart';
import 'package:app/src/constants/constants.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:gap/gap.dart';

import '../home/widgets/widget_card_item.dart';
import '../widgets/widgets.dart';

var cardList = [
  CardData(
      'Andorra',
      'ad.svg',
      'an-doh-rah',
      'The Principality of Andorra is a sovereign landlocked microstate in the eastern Pyrenees, bordered by France and Spain.',
      'Andorra is known for its ski resorts.',
      'Many tourists visit Andorra for its beautiful mountainous landscapes.',
      'Andorra is the sixth smallest nation in Europe.'),
  CardData(
      'United Arab Emirates',
      'ae.svg',
      'yoo-nahy-tid ar-uhb ehm-er-its',
      'A country in Western Asia, located at the southeastern end of the Arabian Peninsula.',
      'Dubai is one of the emirates of the UAE.',
      'The UAE is known for its skyscrapers and luxury shopping.',
      'The Burj Khalifa in Dubai is the tallest building in the world.'),
  CardData(
      'Afghanistan',
      'af.svg',
      'af-gan-uh-stan',
      'A landlocked country located within South Asia and Central Asia.',
      'Afghanistan is known for its rugged terrain.',
      'The country has a rich history dating back to ancient civilizations.',
      'Afghanistan has been a focal point of various empires and cultures.'),
  CardData(
      'Antigua and Barbuda',
      'ag.svg',
      'an-tee-guh and bar-byoo-duh',
      'A twin-island country lying between the Caribbean Sea and the Atlantic Ocean.',
      'Antigua and Barbuda are famous for their beaches.',
      'The country has a vibrant tourism industry.',
      'There are 365 beaches in Antigua, one for each day of the year.'),
  CardData(
      'Anguilla',
      'ai.svg',
      'ang-gwil-uh',
      'A British overseas territory in the Caribbean.',
      'Anguilla is known for its coral reefs and beaches.',
      'Tourism is a significant part of Anguilla’s economy.',
      'The island is a popular destination for snorkeling and diving.'),
  CardData(
      'Albania',
      'al.svg',
      'al-bay-nee-uh',
      'A country in Southeastern Europe on the Adriatic and Ionian Sea within the Mediterranean Sea.',
      'Albania has beautiful mountainous landscapes.',
      'The country has a rich cultural heritage.',
      'Albania is home to numerous castles and archaeological sites.'),
  CardData(
      'Armenia',
      'am.svg',
      'ahr-mee-nee-uh',
      'A country in the South Caucasus region of Eurasia.',
      'Armenia is known for its ancient churches.',
      'The country has a long and storied history.',
      'Armenia is home to the first Christian nation.'),
  CardData(
      'Angola',
      'ao.svg',
      'an-goh-luh',
      'A country in Southern Africa.',
      'Angola is rich in natural resources.',
      'The country has diverse landscapes including deserts and rainforests.',
      'Angola is one of the largest oil producers in Africa.'),
  CardData(
      'Antarctica',
      'aq.svg',
      'an-tahrk-tik-uh',
      'The southernmost continent and site of the South Pole.',
      'Antarctica is known for its icy landscapes.',
      'The continent is mostly uninhabited except for research stations.',
      'Antarctica is the coldest place on Earth.'),
  CardData(
      'Argentina',
      'ar.svg',
      'ahr-juhn-tee-nuh',
      'A country in the southern half of South America.',
      'Argentina is famous for tango music and dance.',
      'The country has diverse landscapes from glaciers to deserts.',
      'Argentina is the eighth largest country in the world by land area.'),
  CardData(
      'American Samoa',
      'c_as.svg',
      'uh-mer-i-kuh n suh-moh-uh',
      'An unincorporated territory of the United States located in the South Pacific Ocean.',
      'American Samoa is known for its beautiful beaches.',
      'The territory has a unique Polynesian culture.',
      'American Samoa is the only U.S. territory south of the equator.'),
  CardData(
      'Austria',
      'at.svg',
      'aw-stree-uh',
      'A landlocked country in Central Europe.',
      'Austria is known for its alpine skiing.',
      'The country has a rich cultural heritage in music and arts.',
      'Austria is the birthplace of famous composer Wolfgang Amadeus Mozart.'),
  CardData(
      'Australia',
      'au.svg',
      'aw-strey-lee-uh',
      'A country and continent surrounded by the Indian and Pacific oceans.',
      'Australia is famous for its unique wildlife.',
      'The country is known for its beautiful beaches and the Great Barrier Reef.',
      'Australia is the sixth largest country by land area.'),
  CardData(
      'Aruba',
      'aw.svg',
      'uh-roo-buh',
      'An island and a constituent country of the Kingdom of the Netherlands in the southern Caribbean Sea.',
      'Aruba is known for its white-sand beaches.',
      'The island is a popular tourist destination.',
      'Aruba enjoys a dry climate, making it a year-round tourist spot.'),
  CardData(
      'Aland Islands',
      'ax.svg',
      'aw-lahnd ahy-luhndz',
      'An archipelago in the Baltic Sea, belonging to Finland.',
      'The Aland Islands are known for their autonomous status.',
      'The archipelago has beautiful natural landscapes.',
      'Aland Islands are a popular destination for sailing and fishing.'),
  CardData(
      'Azerbaijan',
      'az.svg',
      'ah-zer-by-jahn',
      'A country in the South Caucasus region of Eurasia.',
      'Azerbaijan is known for its rich cultural heritage.',
      'The country is rich in oil and natural gas.',
      'Baku, the capital, is famous for its modern architecture.'),
  CardData(
      'Bosnia and Herzegovina',
      'ba.svg',
      'boz-nee-uh and hert-si-goh-vee-nuh',
      'A country on the Balkan Peninsula in Southeastern Europe.',
      'Bosnia and Herzegovina is known for its medieval villages.',
      'The country has a diverse cultural heritage.',
      'Sarajevo, the capital, hosted the 1984 Winter Olympics.'),
  CardData(
      'Barbados',
      'bb.svg',
      'bahr-bay-doz',
      'An island country in the Caribbean region of North America.',
      'Barbados is known for its beautiful beaches.',
      'The country has a rich cultural heritage.',
      'Barbados is the birthplace of rum.'),
  CardData(
      'Bangladesh',
      'bd.svg',
      'bang-gluh-desh',
      'A country in South Asia.',
      'Bangladesh is known for its rich cultural heritage.',
      'The country has beautiful landscapes including the Sundarbans mangrove forest.',
      'Bangladesh is one of the most densely populated countries in the world.'),
  CardData(
      'Belgium',
      'be.svg',
      'bel-juhm',
      'A country in Western Europe.',
      'Belgium is known for its medieval towns and Renaissance architecture.',
      'The country is famous for its chocolate and beer.',
      'Belgium is the administrative center of the EU.'),
  CardData(
      'Burkina Faso',
      'bf.svg',
      'bur-kee-nuh fah-soh',
      'A landlocked country in West Africa.',
      'Burkina Faso is known for its vibrant culture and music.',
      'The country has diverse landscapes including savannas and deserts.',
      'Burkina Faso means "land of honest men."'),
  CardData(
      'Bulgaria',
      'bg.svg',
      'bul-gair-ee-uh',
      'A country in Southeastern Europe.',
      'Bulgaria is known for its rich history and cultural heritage.',
      'The country has beautiful landscapes including mountains and beaches.',
      'Bulgaria is one of the oldest countries in Europe.'),
  CardData(
      'Bahrain',
      'bh.svg',
      'bah-reyn',
      'A country in the Persian Gulf.',
      'Bahrain is known for its modern architecture.',
      'The country has a rich history dating back to ancient civilizations.',
      'Bahrain is an archipelago of 33 islands.'),
  CardData(
      'Burundi',
      'bi.svg',
      'buh-run-dee',
      'A landlocked country in East Africa.',
      'Burundi is known for its beautiful landscapes.',
      'The country has a rich cultural heritage.',
      'Burundi is one of the smallest countries in Africa.'),
  CardData(
      'Benin',
      'bj.svg',
      'buh-nin',
      'A country in West Africa.',
      'Benin is known for its rich cultural heritage.',
      'The country has beautiful landscapes including savannas and beaches.',
      'Benin is the birthplace of the vodun (voodoo) religion.'),
  CardData(
      'Saint Barthelemy',
      'bl.svg',
      'sant bahr-theh-ley-mee',
      'An overseas collectivity of France in the Caribbean.',
      'Saint Barthelemy is known for its luxury tourism.',
      'The island has beautiful beaches and upscale resorts.',
      'Saint Barthelemy is also known as St. Barts.'),
  CardData(
      'Bermuda',
      'bm.svg',
      'ber-myoo-duh',
      'A British Overseas Territory in the North Atlantic Ocean.',
      'Bermuda is known for its pink sand beaches.',
      'The island is a popular destination for tourists.',
      'Bermuda is famous for the Bermuda Triangle myth.'),
  CardData(
      'Brunei',
      'bn.svg',
      'broo-nay',
      'A small country on the island of Borneo in Southeast Asia.',
      'Brunei is known for its wealthy and luxurious lifestyle.',
      'The country has a rich cultural heritage.',
      'Brunei is one of the richest countries in the world due to its oil and gas reserves.'),
  CardData(
      'Bolivia',
      'bo.svg',
      'buh-liv-ee-uh',
      'A landlocked country in central South America.',
      'Bolivia is known for its diverse landscapes.',
      'The country has a rich cultural heritage.',
      'Bolivia has the world\'s largest salt flat, Salar de Uyuni.'),
  CardData(
      'Bonaire, Saint Eustatius and Saba',
      'bq.svg',
      'boh-nair, seynt yoo-stey-shuhs and sey-buh',
      'Special municipalities of the Netherlands in the Caribbean.',
      'These islands are known for their beautiful coral reefs.',
      'Tourism is a significant part of the economy.',
      'The islands are popular for scuba diving and snorkeling.'),
  CardData(
      'Brazil',
      'br.svg',
      'bruh-zil',
      'The largest country in South America.',
      'Brazil is known for its carnival festival.',
      'The country has diverse landscapes including the Amazon rainforest.',
      'Brazil is the fifth largest country in the world by both area and population.'),
  CardData(
      'Bahamas',
      'bs.svg',
      'buh-hah-muhz',
      'A country within the Lucayan Archipelago of the West Indies in the Atlantic.',
      'The Bahamas are known for their beautiful beaches.',
      'The country is a popular tourist destination.',
      'The Bahamas consists of more than 700 islands.'),
  CardData(
      'Bhutan',
      'bt.svg',
      'boo-tahn',
      'A landlocked country in South Asia.',
      'Bhutan is known for its monasteries and fortresses.',
      'The country has a rich cultural heritage.',
      'Bhutan measures its success by Gross National Happiness.'),
  CardData(
      'Bouvet Island',
      'bv.svg',
      'boo-vay ahy-luhnd',
      'An uninhabited subantarctic volcanic island in the South Atlantic Ocean.',
      'Bouvet Island is known for its icy landscapes.',
      'The island is a dependency of Norway.',
      'Bouvet Island is one of the most remote islands in the world.'),
  CardData(
      'Botswana',
      'bw.svg',
      'bot-swah-nuh',
      'A landlocked country in Southern Africa.',
      'Botswana is known for its wildlife and safaris.',
      'The country has diverse landscapes including deserts and wetlands.',
      'Botswana is one of the most sparsely populated countries in the world.'),
  CardData(
      'Belarus',
      'by.svg',
      'bel-uh-roos',
      'A landlocked country in Eastern Europe.',
      'Belarus is known for its Stalinist architecture.',
      'The country has a rich cultural heritage.',
      'Belarus is known as "the lungs of Europe" due to its vast forests.'),
  CardData(
      'Belize',
      'bz.svg',
      'buh-leez',
      'A country on the eastern coast of Central America.',
      'Belize is known for its Caribbean Sea coastline.',
      'The country has a rich cultural heritage.',
      'Belize is home to the second largest barrier reef in the world.'),
  CardData(
      'Canada',
      'ca.svg',
      'kan-uh-duh',
      'A country in North America.',
      'Canada is known for its natural beauty and wildlife.',
      'The country has diverse landscapes including mountains and forests.',
      'Canada is the second largest country in the world by land area.'),
  CardData(
      'Cocos Islands',
      'cc.svg',
      'koh-kohs ahy-luhndz',
      'A territory of Australia in the Indian Ocean.',
      'The Cocos Islands are known for their coral reefs.',
      'The islands are a popular destination for tourists.',
      'The Cocos Islands have a small population of around 600 people.'),
  CardData(
      'Democratic Republic of the Congo',
      'cd.svg',
      'deh-muh-krat-ik ri-puh-blik of the kong-goh',
      'A country located in Central Africa.',
      'The DRC is known for its rich natural resources.',
      'The country has diverse landscapes including rainforests and rivers.',
      'The DRC is the second largest country in Africa by land area.'),
  CardData(
      'Central African Republic',
      'cf.svg',
      'sen-truhl af-ri-kuh n ri-puh-blik',
      'A landlocked country in Central Africa.',
      'The CAR is known for its wildlife and natural beauty.',
      'The country has diverse landscapes including savannas and forests.',
      'The CAR is one of the most sparsely populated countries in Africa.'),
  CardData(
      'Republic of the Congo',
      'cg.svg',
      'ri-puh-blik of the kong-goh',
      'A country located in Central Africa.',
      'The Republic of the Congo is known for its rainforests.',
      'The country has a rich cultural heritage.',
      'The Republic of the Congo is one of the largest producers of oil in Africa.'),
  CardData(
      'Switzerland',
      'ch.svg',
      'swit-ser-luhnd',
      'A landlocked country in Central Europe.',
      'Switzerland is known for its mountains and chocolate.',
      'The country has a rich cultural heritage.',
      'Switzerland is famous for its neutrality in international conflicts.'),
  CardData(
      'Ivory Coast',
      'ci.svg',
      'ahy-vuh-ree kohst',
      'A country located in West Africa.',
      'Ivory Coast is known for its cocoa production.',
      'The country has diverse landscapes including rainforests and beaches.',
      'Ivory Coast is one of the largest producers of cocoa in the world.'),
  CardData(
      'Cook Islands',
      'ck.svg',
      'kook ahy-luhndz',
      'A self-governing island country in the South Pacific Ocean.',
      'The Cook Islands are known for their beautiful beaches.',
      'The islands are a popular destination for tourists.',
      'The Cook Islands have a free association with New Zealand.'),
  CardData(
      'Chile',
      'cl.svg',
      'chil-ee',
      'A country in South America.',
      'Chile is known for its long coastline and diverse landscapes.',
      'The country has a rich cultural heritage.',
      'Chile is the longest north-south trending country in the world.'),
  CardData(
      'Cameroon',
      'cm.svg',
      'kam-uh-roon',
      'A country in Central Africa.',
      'Cameroon is known for its diverse landscapes.',
      'The country has a rich cultural heritage.',
      'Cameroon is often referred to as "Africa in miniature" because of its geographical and cultural diversity.'),
  CardData(
      'China',
      'cn.svg',
      'chahy-nuh',
      'A country in East Asia.',
      'China is known for its ancient civilization and cultural heritage.',
      'The country has diverse landscapes including mountains and deserts.',
      'China is the most populous country in the world.'),
  CardData(
      'Colombia',
      'co.svg',
      'kuh-luhm-bee-uh',
      'A country in South America.',
      'Colombia is known for its coffee and cultural heritage.',
      'The country has diverse landscapes including rainforests and mountains.',
      'Colombia is one of the largest producers of coffee in the world.'),
  CardData(
      'Clipperton Island',
      'cp.svg',
      'klip-er-ton ahy-luhnd',
      'A small, uninhabited coral atoll in the eastern Pacific Ocean.',
      'Clipperton Island is known for its wildlife.',
      'The island is a French overseas territory.',
      'Clipperton Island is one of the most isolated places on Earth.'),
  CardData(
      'Costa Rica',
      'cr.svg',
      'kos-tuh ree-kuh',
      'A country in Central America.',
      'Costa Rica is known for its biodiversity and eco-tourism.',
      'The country has diverse landscapes including rainforests and beaches.',
      'Costa Rica is one of the most environmentally sustainable countries in the world.'),
  CardData(
      'Cuba',
      'cu.svg',
      'kyoo-buh',
      'A country in the Caribbean.',
      'Cuba is known for its vibrant culture and music.',
      'The country has a rich history and cultural heritage.',
      'Cuba is the largest island in the Caribbean.'),
  CardData(
      'Cape Verde',
      'cv.svg',
      'keyp verd',
      'An island country in the central Atlantic Ocean.',
      'Cape Verde is known for its Creole Portuguese-African culture.',
      'The islands have beautiful beaches and landscapes.',
      'Cape Verde is one of the most stable and developed countries in Africa.'),
  CardData(
      'Curacao',
      'cw.svg',
      'kyoo-rah-sow',
      'A Dutch Caribbean island.',
      'Curacao is known for its colorful architecture and beaches.',
      'The island has a rich cultural heritage.',
      'Curacao is a popular tourist destination.'),
  CardData(
      'Christmas Island',
      'cx.svg',
      'kris-muhs ahy-luhnd',
      'An Australian external territory in the Indian Ocean.',
      'Christmas Island is known for its red crab migration.',
      'The island has beautiful landscapes and wildlife.',
      'Christmas Island is named after the day of its discovery.'),
  CardData(
      'Cyprus',
      'cy.svg',
      'sahy-pruhs',
      'An island country in the Eastern Mediterranean.',
      'Cyprus is known for its ancient ruins and beautiful beaches.',
      'The country has a rich cultural heritage.',
      'Cyprus is the third largest and third most populous island in the Mediterranean.'),
  CardData(
      'Czech Republic',
      'cz.svg',
      'chek ri-puh-blik',
      'A country in Central Europe.',
      'The Czech Republic is known for its medieval architecture.',
      'The country has a rich cultural heritage.',
      'The Czech Republic is home to many castles and chateaux.'),
  CardData(
      'Germany',
      'de.svg',
      'jur-muh-nee',
      'A country in Central Europe.',
      'Germany is known for its beer and Oktoberfest.',
      'The country has a rich cultural heritage.',
      'Germany is one of the largest economies in the world.'),
  CardData(
      'Diego Garcia',
      'dg.svg',
      'dee-ey-goh gahr-see-uh',
      'An atoll in the Indian Ocean.',
      'Diego Garcia is known for its strategic military base.',
      'The island is a British Indian Ocean Territory.',
      'Diego Garcia is one of the most remote locations in the world.'),
  CardData(
      'Djibouti',
      'dj.svg',
      'ji-boo-tee',
      'A country in the Horn of Africa.',
      'Djibouti is known for its strategic location near the Red Sea.',
      'The country has a rich cultural heritage.',
      'Djibouti is one of the smallest countries in Africa.'),
  CardData(
      'Denmark',
      'dk.svg',
      'den-mahrk',
      'A country in Northern Europe.',
      'Denmark is known for its Vikings and castles.',
      'The country has a rich cultural heritage.',
      'Denmark is one of the happiest countries in the world.'),
  CardData(
      'Dominica',
      'dm.svg',
      'dom-in-ee-kuh',
      'An island country in the Caribbean.',
      'Dominica is known for its natural beauty and hot springs.',
      'The country has a rich cultural heritage.',
      'Dominica is home to the second largest boiling lake in the world.'),
  CardData(
      'Dominican Republic',
      'c_do.svg',
      'duh-min-i-kuh n ri-puh-blik',
      'A country on the island of Hispaniola in the Caribbean.',
      'The Dominican Republic is known for its beaches and resorts.',
      'The country has a rich cultural heritage.',
      'The Dominican Republic is the most visited destination in the Caribbean.'),
  CardData(
      'Algeria',
      'dz.svg',
      'al-jeer-ee-uh',
      'A country in North Africa.',
      'Algeria is known for its Sahara Desert.',
      'The country has a rich cultural heritage.',
      'Algeria is the largest country in Africa by land area.'),
  CardData(
      'Ceuta and Melilla',
      'ea.svg',
      'see-oo-tuh and meh-lee-yuh',
      'Two autonomous cities of Spain located on the north coast of Africa.',
      'Ceuta and Melilla are known for their unique cultural blend.',
      'The cities have a rich cultural heritage.',
      'Ceuta and Melilla are the only two Spanish territories in mainland Africa.'),
  CardData(
      'Ecuador',
      'ec.svg',
      'ek-wuh-dawr',
      'A country in South America.',
      'Ecuador is known for its biodiversity and the Galapagos Islands.',
      'The country has diverse landscapes including mountains and rainforests.',
      'Ecuador is one of the most biodiverse countries in the world.'),
  CardData(
      'Estonia',
      'ee.svg',
      'e-stoh-nee-uh',
      'A country in Northern Europe.',
      'Estonia is known for its medieval architecture and digital advancements.',
      'The country has a rich cultural heritage.',
      'Estonia is one of the most digitally advanced countries in the world.'),
  CardData(
      'Egypt',
      'eg.svg',
      'ee-jipt',
      'A country in North Africa.',
      'Egypt is known for its ancient civilization and pyramids.',
      'The country has a rich cultural heritage.',
      'Egypt is home to one of the world\'s oldest civilizations.'),
  CardData(
      'Western Sahara',
      'eh.svg',
      'wes-tern suh-hahr-uh',
      'A disputed territory in North Africa.',
      'Western Sahara is known for its desert landscapes.',
      'The territory has a rich cultural heritage.',
      'Western Sahara is one of the most sparsely populated regions in the world.'),
  CardData(
      'Eritrea',
      'er.svg',
      'eh-ri-tree-uh',
      'A country in the Horn of Africa.',
      'Eritrea is known for its Red Sea coastline.',
      'The country has a rich cultural heritage.',
      'Eritrea is one of the youngest countries in Africa.'),
  CardData(
      'Spain',
      'es.svg',
      'speyn',
      'A country in Southwestern Europe.',
      'Spain is known for its vibrant culture and history.',
      'The country has a rich cultural heritage.',
      'Spain is the fourth largest country in Europe by land area.'),
  CardData(
      'Ethiopia',
      'et.svg',
      'ee-thee-oh-pee-uh',
      'A country in the Horn of Africa.',
      'Ethiopia is known for its ancient culture and history.',
      'The country has a rich cultural heritage.',
      'Ethiopia is one of the oldest countries in the world.'),
  CardData(
      'European Union',
      'eu.svg',
      'yoo-roh-pee-uhn yoo-nyuhn',
      'A political and economic union of 27 member states located primarily in Europe.',
      'The EU is known for its single market and currency, the euro.',
      'The union has a rich cultural heritage.',
      'The EU is the largest economic bloc in the world.'),
  CardData(
      'Finland',
      'fi.svg',
      'fin-luhnd',
      'A country in Northern Europe.',
      'Finland is known for its forests and lakes.',
      'The country has a rich cultural heritage.',
      'Finland is one of the happiest countries in the world.'),
  CardData(
      'Fiji',
      'fj.svg',
      'fee-jee',
      'An island country in the South Pacific Ocean.',
      'Fiji is known for its beautiful beaches and coral reefs.',
      'The country has a rich cultural heritage.',
      'Fiji is a popular destination for tourists.'),
  CardData(
      'Falkland Islands',
      'fk.svg',
      'fawk-luhnd ahy-luhndz',
      'A British Overseas Territory in the South Atlantic Ocean.',
      'The Falkland Islands are known for their wildlife.',
      'The islands have a rich cultural heritage.',
      'The Falkland Islands are home to many species of birds and marine mammals.'),
  CardData(
      'Micronesia',
      'fm.svg',
      'mahy-kroh-nee-zhuh',
      'A country in the western Pacific Ocean.',
      'Micronesia is known for its beautiful islands and coral reefs.',
      'The country has a rich cultural heritage.',
      'Micronesia is composed of over 600 islands.'),
  CardData(
      'Faroe Islands',
      'fo.svg',
      'fey-roh ahy-luhndz',
      'An autonomous territory within the Kingdom of Denmark.',
      'The Faroe Islands are known for their dramatic landscapes.',
      'The islands have a rich cultural heritage.',
      'The Faroe Islands are home to many species of seabirds.'),
  CardData(
      'France',
      'fr.svg',
      'frans',
      'A country in Western Europe.',
      'France is known for its culture, cuisine, and landmarks.',
      'The country has a rich cultural heritage.',
      'France is the most visited country in the world.'),
  CardData(
      'Gabon',
      'ga.svg',
      'gah-bon',
      'A country in Central Africa.',
      'Gabon is known for its rainforests and wildlife.',
      'The country has a rich cultural heritage.',
      'Gabon is one of the most urbanized countries in Africa.'),
  CardData(
      'United Kingdom',
      'uk.svg',
      'yoo-nahy-tid king-duhm',
      'A country in Europe.',
      'The UK is known for its history and culture.',
      'The country has a rich cultural heritage.',
      'The UK consists of four countries: England, Scotland, Wales, and Northern Ireland.'),
  CardData(
      'Great Britain',
      'gb.svg',
      'greyt brit-n',
      'An island in Europe.',
      'Great Britain is known for its history and culture.',
      'The island has a rich cultural heritage.',
      'Great Britain consists of England, Scotland, and Wales.'),
  CardData(
      'Grenada',
      'gd.svg',
      'gruh-ney-duh',
      'A country in the Caribbean.',
      'Grenada is known for its spices and beaches.',
      'The country has a rich cultural heritage.',
      'Grenada is often referred to as the "Spice Isle" because of its production of nutmeg and mace.'),
  CardData(
      'Georgia',
      'ge.svg',
      'jawr-juh',
      'A country in the Caucasus region.',
      'Georgia is known for its mountains and wine.',
      'The country has a rich cultural heritage.',
      'Georgia is one of the oldest wine-producing regions in the world.'),
  CardData(
      'French Guiana',
      'gf.svg',
      'french gee-ah-nuh',
      'An overseas department of France in South America.',
      'French Guiana is known for its rainforests and spaceport.',
      'The department has a rich cultural heritage.',
      'French Guiana is home to the Guiana Space Centre, a major spaceport.'),
  CardData(
      'Guernsey',
      'gg.svg',
      'gern-zee',
      'A British Crown dependency in the English Channel.',
      'Guernsey is known for its beautiful landscapes.',
      'The island has a rich cultural heritage.',
      'Guernsey is one of the Channel Islands.'),
  CardData(
      'Ghana',
      'gh.svg',
      'gah-nuh',
      'A country in West Africa.',
      'Ghana is known for its gold and cocoa.',
      'The country has a rich cultural heritage.',
      'Ghana was the first African country to gain independence from colonial rule.'),
  CardData(
      'Gibraltar',
      'gi.svg',
      'juh-brawl-tur',
      'A British Overseas Territory located at the southern tip of the Iberian Peninsula.',
      'Gibraltar is known for its Rock and strategic location.',
      'The territory has a rich cultural heritage.',
      'Gibraltar is famous for its limestone Rock, which has a network of tunnels.'),
  CardData(
      'Greenland',
      'gl.svg',
      'green-luhnd',
      'An autonomous territory within the Kingdom of Denmark.',
      'Greenland is known for its glaciers and icebergs.',
      'The territory has a rich cultural heritage.',
      'Greenland is the world\'s largest island.'),
  CardData(
      'Gambia',
      'gm.svg',
      'gam-bee-uh',
      'A country in West Africa.',
      'The Gambia is known for its river and wildlife.',
      'The country has a rich cultural heritage.',
      'The Gambia is the smallest country on mainland Africa.'),
  CardData(
      'Guinea',
      'gn.svg',
      'gin-ee',
      'A country in West Africa.',
      'Guinea is known for its mineral wealth.',
      'The country has a rich cultural heritage.',
      'Guinea is one of the world\'s largest producers of bauxite.'),
  CardData(
      'Guadeloupe',
      'gp.svg',
      'gwah-dl-oop',
      'An overseas region of France in the Caribbean.',
      'Guadeloupe is known for its beautiful beaches.',
      'The region has a rich cultural heritage.',
      'Guadeloupe consists of several islands, the two largest being Basse-Terre and Grande-Terre.'),
  CardData(
      'Equatorial Guinea',
      'gq.svg',
      'e-kwuh-tawr-ee-uhl gin-ee',
      'A country in Central Africa.',
      'Equatorial Guinea is known for its oil and gas reserves.',
      'The country has a rich cultural heritage.',
      'Equatorial Guinea is the only African country where Spanish is an official language.'),
  CardData(
      'Greece',
      'gr.svg',
      'grees',
      'A country in Southeastern Europe.',
      'Greece is known for its ancient civilization and islands.',
      'The country has a rich cultural heritage.',
      'Greece is considered the cradle of Western civilization.'),
  CardData(
      'South Georgia and the South Sandwich Islands',
      'gs.svg',
      'south jawr-juh and the south sand-wich ahy-luhndz',
      'A British Overseas Territory in the southern Atlantic Ocean.',
      'These islands are known for their wildlife and remote location.',
      'The territory has a rich cultural heritage.',
      'South Georgia and the South Sandwich Islands are home to many species of seabirds and marine mammals.'),
  CardData(
      'Guatemala',
      'gt.svg',
      'gwah-tuh-mah-luh',
      'A country in Central America.',
      'Guatemala is known for its Mayan ruins and coffee.',
      'The country has a rich cultural heritage.',
      'Guatemala is home to the ancient city of Tikal, a UNESCO World Heritage Site.'),
  CardData(
      'Guam',
      'gu.svg',
      'gwahm',
      'An unincorporated territory of the United States in the western Pacific Ocean.',
      'Guam is known for its strategic military bases.',
      'The territory has a rich cultural heritage.',
      'Guam is the largest and southernmost of the Mariana Islands.'),
  CardData(
      'Guinea-Bissau',
      'gw.svg',
      'gin-ee-bi-sow',
      'A country in West Africa.',
      'Guinea-Bissau is known for its national parks and wildlife.',
      'The country has a rich cultural heritage.',
      'Guinea-Bissau is one of the world\'s poorest countries.'),
  CardData(
      'Guyana',
      'gy.svg',
      'gahy-ah-nuh',
      'A country in South America.',
      'Guyana is known for its natural beauty and wildlife.',
      'The country has a rich cultural heritage.',
      'Guyana is the only English-speaking country in South America.'),
  CardData(
      'Hong Kong',
      'hk.svg',
      'hawng kong',
      'A Special Administrative Region of China.',
      'Hong Kong is known for its skyline and harbor.',
      'The region has a rich cultural heritage.',
      'Hong Kong is one of the world\'s leading financial centers.'),
  CardData(
      'Heard Island and McDonald Islands',
      'hm.svg',
      'hurd ahy-luhnd and mik-don-uhld ahy-luhndz',
      'An Australian external territory in the southern Indian Ocean.',
      'These islands are known for their volcanic activity.',
      'The territory has a rich natural heritage.',
      'Heard Island is home to Australia\'s only active volcano, Big Ben.'),
  CardData(
      'Honduras',
      'hn.svg',
      'hon-doo-ruhs',
      'A country in Central America.',
      'Honduras is known for its Mayan ruins and beaches.',
      'The country has a rich cultural heritage.',
      'Honduras is home to the ancient city of Copan, a UNESCO World Heritage Site.'),
  CardData(
      'Croatia',
      'hr.svg',
      'kroh-ey-shuh',
      'A country in Southeastern Europe.',
      'Croatia is known for its beautiful coastline and islands.',
      'The country has a rich cultural heritage.',
      'Croatia is home to the ancient city of Dubrovnik, a UNESCO World Heritage Site.'),
  CardData(
      'Haiti',
      'ht.svg',
      'hey-tee',
      'A country in the Caribbean.',
      'Haiti is known for its vibrant culture and history.',
      'The country has a rich cultural heritage.',
      'Haiti is the first independent nation of Latin America and the Caribbean.'),
  CardData(
      'Hungary',
      'hu.svg',
      'huhng-guh-ree',
      'A country in Central Europe.',
      'Hungary is known for its architecture and thermal baths.',
      'The country has a rich cultural heritage.',
      'Hungary is home to the largest thermal water cave system in the world.'),
  CardData(
      'Indonesia',
      'id.svg',
      'in-duh-nee-zhuh',
      'A country in Southeast Asia.',
      'Indonesia is known for its islands and volcanoes.',
      'The country has a rich cultural heritage.',
      'Indonesia is the world\'s largest archipelago.'),
  CardData(
      'Ireland',
      'ie.svg',
      'ahyuh r-luhnd',
      'A country in Europe.',
      'Ireland is known for its green landscapes and castles.',
      'The country has a rich cultural heritage.',
      'Ireland is known as the "Emerald Isle" due to its lush greenery.'),
  CardData(
      'Israel',
      'il.svg',
      'iz-ree-uhl',
      'A country in the Middle East.',
      'Israel is known for its historical and religious significance.',
      'The country has a rich cultural heritage.',
      'Israel is home to many important religious sites.'),
  CardData(
      'Isle of Man',
      'im.svg',
      'ahyl uhv man',
      'A British Crown dependency in the Irish Sea.',
      'The Isle of Man is known for its motorcycle races.',
      'The island has a rich cultural heritage.',
      'The Isle of Man is home to the world\'s oldest continuous parliament, Tynwald.'),
  CardData(
      'India',
      'in.svg',
      'in-dee-uh',
      'A country in South Asia.',
      'India is known for its diverse culture and history.',
      'The country has a rich cultural heritage.',
      'India is the second most populous country in the world.'),
  CardData(
      'British Indian Ocean Territory',
      'io.svg',
      'brit-ish in-dee-uhn oh-shuhn ter-i-tawr-ee',
      'A British Overseas Territory in the Indian Ocean.',
      'The territory is known for its military base on Diego Garcia.',
      'The territory has a strategic location.',
      'The British Indian Ocean Territory is one of the most remote territories in the world.'),
  CardData(
      'Iraq',
      'iq.svg',
      'i-rak',
      'A country in the Middle East.',
      'Iraq is known for its ancient Mesopotamian heritage.',
      'The country has a rich cultural heritage.',
      'Iraq is home to the ancient city of Babylon.'),
  CardData(
      'Iran',
      'ir.svg',
      'ih-rahn',
      'A country in the Middle East.',
      'Iran is known for its Persian culture and history.',
      'The country has a rich cultural heritage.',
      'Iran is home to many ancient ruins and historical sites.'),
  CardData(
      'Iceland',
      'is.svg',
      'ahy-suh-luhnd',
      'A country in Northern Europe.',
      'Iceland is known for its glaciers and geothermal activity.',
      'The country has a rich natural heritage.',
      'Iceland is home to many volcanoes and hot springs.'),
  CardData(
      'Italy',
      'it.svg',
      'it-lee',
      'A country in Southern Europe.',
      'Italy is known for its art, architecture, and cuisine.',
      'The country has a rich cultural heritage.',
      'Italy is home to the largest number of UNESCO World Heritage Sites.'),
  CardData(
      'Jersey',
      'je.svg',
      'jur-zee',
      'A British Crown dependency in the English Channel.',
      'Jersey is known for its beaches and countryside.',
      'The island has a rich cultural heritage.',
      'Jersey is the largest of the Channel Islands.'),
  CardData(
      'Jamaica',
      'jm.svg',
      'juh-mey-kuh',
      'A country in the Caribbean.',
      'Jamaica is known for its music and culture.',
      'The country has a rich cultural heritage.',
      'Jamaica is the birthplace of reggae music.'),
  CardData(
      'Jordan',
      'jo.svg',
      'jawr-dn',
      'A country in the Middle East.',
      'Jordan is known for its ancient ruins and desert landscapes.',
      'The country has a rich cultural heritage.',
      'Jordan is home to the ancient city of Petra, a UNESCO World Heritage Site.'),
  CardData(
      'Japan',
      'jp.svg',
      'juh-pan',
      'A country in East Asia.',
      'Japan is known for its technology and culture.',
      'The country has a rich cultural heritage.',
      'Japan is home to many ancient temples and modern cities.'),
  CardData(
      'Kenya',
      'ke.svg',
      'ken-yuh',
      'A country in East Africa.',
      'Kenya is known for its wildlife and safaris.',
      'The country has diverse landscapes including savannas and mountains.',
      'Kenya is one of the most popular tourist destinations in Africa.'),
  CardData(
      'Kyrgyzstan',
      'kg.svg',
      'kir-gih-stan',
      'A country in Central Asia.',
      'Kyrgyzstan is known for its mountains and lakes.',
      'The country has a rich cultural heritage.',
      'Kyrgyzstan is home to the Tien Shan mountain range.'),
  CardData(
      'Cambodia',
      'kh.svg',
      'kam-boh-dee-uh',
      'A country in Southeast Asia.',
      'Cambodia is known for its ancient temples and rich history.',
      'The country has a rich cultural heritage.',
      'Cambodia is home to Angkor Wat, the largest religious monument in the world.'),
  CardData(
      'Kiribati',
      'ki.svg',
      'keer-ih-bas',
      'A country in the central Pacific Ocean.',
      'Kiribati is known for its atolls and marine life.',
      'The country has a rich cultural heritage.',
      'Kiribati is one of the most isolated countries in the world.'),
  CardData(
      'Comoros',
      'km.svg',
      'kom-uh-rohz',
      'A country in the Indian Ocean.',
      'Comoros is known for its beaches and marine life.',
      'The country has a rich cultural heritage.',
      'Comoros is one of the smallest countries in Africa.'),
  CardData(
      'Saint Kitts and Nevis',
      'kn.svg',
      'seynt kits and nee-vis',
      'A country in the Caribbean.',
      'Saint Kitts and Nevis is known for its beaches and mountains.',
      'The country has a rich cultural heritage.',
      'Saint Kitts and Nevis is the smallest sovereign state in the Western Hemisphere.'),
  CardData(
      'North Korea',
      'kp.svg',
      'nawth kuh-ree-uh',
      'A country in East Asia.',
      'North Korea is known for its secrecy and isolation.',
      'The country has a rich cultural heritage.',
      'North Korea is one of the most isolated countries in the world.'),
  CardData(
      'South Korea',
      'kr.svg',
      'south kuh-ree-uh',
      'A country in East Asia.',
      'South Korea is known for its technology and pop culture.',
      'The country has a rich cultural heritage.',
      'South Korea is one of the most technologically advanced countries in the world.'),
  CardData(
      'Kuwait',
      'kw.svg',
      'koo-weyt',
      'A country in the Middle East.',
      'Kuwait is known for its oil reserves.',
      'The country has a rich cultural heritage.',
      'Kuwait has one of the highest per capita incomes in the world.'),
  CardData(
      'Cayman Islands',
      'ky.svg',
      'key-muhn ahy-luhndz',
      'A British Overseas Territory in the Caribbean.',
      'The Cayman Islands are known for their beaches and diving sites.',
      'The territory has a rich cultural heritage.',
      'The Cayman Islands are a major financial center.'),
  CardData(
      'Kazakhstan',
      'kz.svg',
      'kaz-ak-stan',
      'A country in Central Asia.',
      'Kazakhstan is known for its vast steppes and natural resources.',
      'The country has a rich cultural heritage.',
      'Kazakhstan is the largest landlocked country in the world.'),
  CardData(
      'Laos',
      'la.svg',
      'lah-ohs',
      'A country in Southeast Asia.',
      'Laos is known for its mountains and Buddhist temples.',
      'The country has a rich cultural heritage.',
      'Laos is one of the least densely populated countries in Asia.'),
  CardData(
      'Lebanon',
      'lb.svg',
      'leb-uh-non',
      'A country in the Middle East.',
      'Lebanon is known for its history and cuisine.',
      'The country has a rich cultural heritage.',
      'Lebanon is one of the oldest countries in the world.'),
  CardData(
      'Saint Lucia',
      'lc.svg',
      'seynt loo-shuh',
      'A country in the Caribbean.',
      'Saint Lucia is known for its beaches and mountains.',
      'The country has a rich cultural heritage.',
      'Saint Lucia is home to the Pitons, a UNESCO World Heritage Site.'),
  CardData(
      'Liechtenstein',
      'li.svg',
      'lik-tuhn-shtahyn',
      'A country in Europe.',
      'Liechtenstein is known for its castles and mountains.',
      'The country has a rich cultural heritage.',
      'Liechtenstein is one of the smallest countries in the world.'),
  CardData(
      'Sri Lanka',
      'lk.svg',
      'sree lahng-kuh',
      'A country in South Asia.',
      'Sri Lanka is known for its beaches and tea plantations.',
      'The country has a rich cultural heritage.',
      'Sri Lanka is often referred to as the "Pearl of the Indian Ocean."'),
  CardData(
      'Liberia',
      'lr.svg',
      'lahy-beer-ee-uh',
      'A country in West Africa.',
      'Liberia is known for its history and wildlife.',
      'The country has a rich cultural heritage.',
      'Liberia was founded by freed American slaves.'),
  CardData(
      'Lesotho',
      'ls.svg',
      'li-soo-too',
      'A country in Southern Africa.',
      'Lesotho is known for its mountains and rich culture.',
      'The country has a rich cultural heritage.',
      'Lesotho is the only country in the world entirely above 1,000 meters in elevation.'),
  CardData(
      'Lithuania',
      'lt.svg',
      'lith-yoo-ey-nee-uh',
      'A country in Europe.',
      'Lithuania is known for its medieval architecture and forests.',
      'The country has a rich cultural heritage.',
      'Lithuania was the first republic to declare independence from the Soviet Union.'),
  CardData(
      'Luxembourg',
      'lu.svg',
      'luhk-suhm-burg',
      'A country in Europe.',
      'Luxembourg is known for its wealth and castles.',
      'The country has a rich cultural heritage.',
      'Luxembourg is one of the smallest countries in Europe.'),
  CardData(
      'Latvia',
      'lv.svg',
      'lat-vee-uh',
      'A country in Europe.',
      'Latvia is known for its forests and medieval architecture.',
      'The country has a rich cultural heritage.',
      'Latvia is one of the greenest countries in the world.'),
  CardData(
      'Libya',
      'ly.svg',
      'lib-ee-uh',
      'A country in North Africa.',
      'Libya is known for its deserts and ancient ruins.',
      'The country has a rich cultural heritage.',
      'Libya has one of the largest proven oil reserves in Africa.'),
  CardData(
      'Morocco',
      'ma.svg',
      'muh-rok-oh',
      'A country in North Africa.',
      'Morocco is known for its culture and history.',
      'The country has a rich cultural heritage.',
      'Morocco is home to the Sahara Desert and the Atlas Mountains.'),
  CardData(
      'Monaco',
      'mc.svg',
      'mon-uh-koh',
      'A small country in Europe.',
      'Monaco is known for its wealth and casinos.',
      'The country has a rich cultural heritage.',
      'Monaco is the second smallest country in the world.'),
  CardData(
      'Moldova',
      'md.svg',
      'mohl-doh-vuh',
      'A country in Eastern Europe.',
      'Moldova is known for its wine and monasteries.',
      'The country has a rich cultural heritage.',
      'Moldova is one of the least visited countries in Europe.'),
  CardData(
      'Montenegro',
      'me.svg',
      'mon-tuh-ney-groh',
      'A country in Southeastern Europe.',
      'Montenegro is known for its mountains and coastline.',
      'The country has a rich cultural heritage.',
      'Montenegro is one of the youngest countries in the world.'),
  CardData(
      'Saint Martin',
      'mf.svg',
      'seynt mahr-tin',
      'An overseas collectivity of France in the Caribbean.',
      'Saint Martin is known for its beaches and resorts.',
      'The collectivity has a rich cultural heritage.',
      'Saint Martin is the smallest island in the world shared by two countries.'),
  CardData(
      'Madagascar',
      'mg.svg',
      'mad-uh-gas-kar',
      'An island country in the Indian Ocean.',
      'Madagascar is known for its biodiversity and unique wildlife.',
      'The country has a rich natural heritage.',
      'Madagascar is home to many species found nowhere else on Earth.'),
  CardData(
      'Marshall Islands',
      'mh.svg',
      'mahr-shuhl ahy-luhndz',
      'A country in the central Pacific Ocean.',
      'The Marshall Islands are known for their atolls and marine life.',
      'The country has a rich cultural heritage.',
      'The Marshall Islands are home to the Bikini Atoll, a former nuclear testing site.'),
  CardData(
      'North Macedonia',
      'mk.svg',
      'nawrth mas-uh-doh-nee-uh',
      'A country in Southeastern Europe.',
      'North Macedonia is known for its history and culture.',
      'The country has a rich cultural heritage.',
      'North Macedonia is home to many ancient ruins and historical sites.'),
  CardData(
      'Mali',
      'ml.svg',
      'mah-lee',
      'A country in West Africa.',
      'Mali is known for its music and culture.',
      'The country has a rich cultural heritage.',
      'Mali is home to the ancient city of Timbuktu, a UNESCO World Heritage Site.'),
  CardData(
      'Myanmar',
      'mm.svg',
      'mee-an-mahr',
      'A country in Southeast Asia.',
      'Myanmar is known for its temples and pagodas.',
      'The country has a rich cultural heritage.',
      'Myanmar is home to thousands of Buddhist temples and pagodas.'),
  CardData(
      'Mongolia',
      'mn.svg',
      'mon-goh-lee-uh',
      'A country in East Asia.',
      'Mongolia is known for its nomadic culture and vast landscapes.',
      'The country has a rich cultural heritage.',
      'Mongolia is the most sparsely populated country in the world.'),
  CardData(
      'Macau',
      'mo.svg',
      'muh-kow',
      'A Special Administrative Region of China.',
      'Macau is known for its casinos and Portuguese heritage.',
      'The region has a rich cultural heritage.',
      'Macau is often referred to as the "Las Vegas of Asia."'),
  CardData(
      'Northern Mariana Islands',
      'mp.svg',
      'nawr-thurn mar-ee-ah-nuh ahy-luhndz',
      'A Commonwealth of the United States in the Pacific Ocean.',
      'The Northern Mariana Islands are known for their beaches and diving sites.',
      'The commonwealth has a rich cultural heritage.',
      'The Northern Mariana Islands consist of 14 islands.'),
  CardData(
      'Martinique',
      'mq.svg',
      'mahr-tn-eek',
      'An overseas region of France in the Caribbean.',
      'Martinique is known for its beaches and volcanic activity.',
      'The region has a rich cultural heritage.',
      'Martinique is home to Mount Pelée, an active volcano.'),
  CardData(
      'Mauritania',
      'mr.svg',
      'mawr-ih-tey-nee-uh',
      'A country in West Africa.',
      'Mauritania is known for its deserts and nomadic culture.',
      'The country has a rich cultural heritage.',
      'Mauritania is one of the least densely populated countries in the world.'),
  CardData(
      'Montserrat',
      'ms.svg',
      'mont-ser-at',
      'A British Overseas Territory in the Caribbean.',
      'Montserrat is known for its volcanic activity.',
      'The territory has a rich cultural heritage.',
      'Montserrat is home to the Soufrière Hills volcano.'),
  CardData(
      'Malta',
      'mt.svg',
      'mawl-tuh',
      'A country in Southern Europe.',
      'Malta is known for its history and architecture.',
      'The country has a rich cultural heritage.',
      'Malta is one of the world\'s smallest and most densely populated countries.'),
  CardData(
      'Mauritius',
      'mu.svg',
      'muh-rish-uhs',
      'A country in the Indian Ocean.',
      'Mauritius is known for its beaches and marine life.',
      'The country has a rich cultural heritage.',
      'Mauritius is home to many unique species, including the now-extinct dodo bird.'),
  CardData(
      'Maldives',
      'mv.svg',
      'mawl-deevz',
      'A country in the Indian Ocean.',
      'The Maldives are known for their beaches and marine life.',
      'The country has a rich cultural heritage.',
      'The Maldives is the lowest-lying country in the world.'),
  CardData(
      'Malawi',
      'mw.svg',
      'muh-lah-wee',
      'A country in Southeastern Africa.',
      'Malawi is known for its lakes and wildlife.',
      'The country has a rich cultural heritage.',
      'Malawi is home to Lake Malawi, one of the largest lakes in Africa.'),
  CardData(
      'Mexico',
      'mx.svg',
      'mek-si-koh',
      'A country in North America.',
      'Mexico is known for its culture, cuisine, and history.',
      'The country has a rich cultural heritage.',
      'Mexico is home to many ancient civilizations, including the Aztec and Maya.'),
  CardData(
      'Malaysia',
      'my.svg',
      'muh-ley-zhuh',
      'A country in Southeast Asia.',
      'Malaysia is known for its beaches, rainforests, and mix of cultures.',
      'The country has a rich cultural heritage.',
      'Malaysia is home to the Petronas Towers, the tallest twin towers in the world.'),
  CardData(
      'Mozambique',
      'mz.svg',
      'moh-zam-beek',
      'A country in Southeastern Africa.',
      'Mozambique is known for its beaches and marine life.',
      'The country has a rich cultural heritage.',
      'Mozambique is home to many national parks and reserves.'),
  CardData(
      'Namibia',
      'na.svg',
      'nuh-mib-ee-uh',
      'A country in Southern Africa.',
      'Namibia is known for its deserts and wildlife.',
      'The country has a rich cultural heritage.',
      'Namibia is home to the Namib Desert, one of the oldest deserts in the world.'),
  CardData(
      'New Caledonia',
      'nc.svg',
      'nyoo kal-uh-doh-nee-uh',
      'A French territory in the South Pacific.',
      'New Caledonia is known for its beaches and marine life.',
      'The territory has a rich cultural heritage.',
      'New Caledonia is home to one of the largest lagoons in the world.'),
  CardData(
      'Niger',
      'ne.svg',
      'nee-zher',
      'A country in West Africa.',
      'Niger is known for its deserts and wildlife.',
      'The country has a rich cultural heritage.',
      'Niger is one of the hottest countries in the world.'),
  CardData(
      'Norfolk Island',
      'nf.svg',
      'nawr-fuhk ahy-luhnd',
      'An Australian external territory in the Pacific Ocean.',
      'Norfolk Island is known for its pine trees and history.',
      'The territory has a rich cultural heritage.',
      'Norfolk Island was once a penal colony.'),
  CardData(
      'Nigeria',
      'ng.svg',
      'nahy-jeer-ee-uh',
      'A country in West Africa.',
      'Nigeria is known for its culture and diversity.',
      'The country has a rich cultural heritage.',
      'Nigeria is the most populous country in Africa.'),
  CardData(
      'Nicaragua',
      'ni.svg',
      'nik-uh-rah-gwuh',
      'A country in Central America.',
      'Nicaragua is known for its lakes and volcanoes.',
      'The country has a rich cultural heritage.',
      'Nicaragua is home to the largest lake in Central America, Lake Nicaragua.'),
  CardData(
      'Netherlands',
      'nl.svg',
      'neth-er-luhndz',
      'A country in Europe.',
      'The Netherlands is known for its canals, tulips, and windmills.',
      'The country has a rich cultural heritage.',
      'The Netherlands is one of the most densely populated countries in Europe.'),
  CardData(
      'Norway',
      'no.svg',
      'nawr-wey',
      'A country in Northern Europe.',
      'Norway is known for its fjords and natural beauty.',
      'The country has a rich cultural heritage.',
      'Norway is one of the most prosperous countries in the world.'),
  CardData(
      'Nepal',
      'np.svg',
      'nuh-pahl',
      'A country in South Asia.',
      'Nepal is known for its mountains and trekking routes.',
      'The country has a rich cultural heritage.',
      'Nepal is home to Mount Everest, the highest peak in the world.'),
  CardData(
      'Nauru',
      'nr.svg',
      'nah-roo',
      'A country in the Pacific Ocean.',
      'Nauru is known for its phosphate mining.',
      'The country has a rich cultural heritage.',
      'Nauru is the third smallest country in the world by land area.'),
  CardData(
      'Niue',
      'nu.svg',
      'nyoo-ay',
      'A self-governing territory in free association with New Zealand.',
      'Niue is known for its coral reefs and caves.',
      'The territory has a rich cultural heritage.',
      'Niue is one of the world\'s largest coral islands.'),
  CardData(
      'New Zealand',
      'nz.svg',
      'nyoo zee-luhnd',
      'A country in the southwestern Pacific Ocean.',
      'New Zealand is known for its landscapes and Maori culture.',
      'The country has a rich cultural heritage.',
      'New Zealand is one of the most geographically isolated countries in the world.'),
  CardData(
      'Oman',
      'om.svg',
      'oh-mahn',
      'A country in the Middle East.',
      'Oman is known for its deserts, mountains, and beaches.',
      'The country has a rich cultural heritage.',
      'Oman is one of the oldest independent states in the Arab world.'),
  CardData(
      'Panama',
      'pa.svg',
      'pan-uh-mah',
      'A country in Central America.',
      'Panama is known for its canal and biodiversity.',
      'The country has a rich cultural heritage.',
      'Panama is the only place in the world where you can see the sun rise on the Pacific and set on the Atlantic.'),
  CardData(
      'Peru',
      'pe.svg',
      'puh-roo',
      'A country in South America.',
      'Peru is known for its ancient civilizations and cuisine.',
      'The country has a rich cultural heritage.',
      'Peru is home to Machu Picchu, one of the New Seven Wonders of the World.'),
  CardData(
      'French Polynesia',
      'pf.svg',
      'french pol-uh-nee-zhuh',
      'An overseas collectivity of France in the South Pacific.',
      'French Polynesia is known for its islands and marine life.',
      'The collectivity has a rich cultural heritage.',
      'French Polynesia is home to the island of Tahiti.'),
  CardData(
      'Papua New Guinea',
      'pg.svg',
      'pap-yoo-uh nyoo gin-ee',
      'A country in Oceania.',
      'Papua New Guinea is known for its cultural diversity and rainforests.',
      'The country has a rich cultural heritage.',
      'Papua New Guinea is one of the most culturally diverse countries in the world.'),
  CardData(
      'Philippines',
      'ph.svg',
      'fil-uh-peenz',
      'A country in Southeast Asia.',
      'The Philippines is known for its beaches and biodiversity.',
      'The country has a rich cultural heritage.',
      'The Philippines is an archipelago of over 7,000 islands.'),
  CardData(
      'Pakistan',
      'pk.svg',
      'pak-uh-stan',
      'A country in South Asia.',
      'Pakistan is known for its mountains and cultural heritage.',
      'The country has a rich cultural heritage.',
      'Pakistan is home to the second highest peak in the world, K2.'),
  CardData(
      'Poland',
      'pl.svg',
      'poh-luhnd',
      'A country in Europe.',
      'Poland is known for its history and medieval architecture.',
      'The country has a rich cultural heritage.',
      'Poland is home to the largest castle in the world, Malbork Castle.'),
  CardData(
      'Saint Pierre and Miquelon',
      'pm.svg',
      'seynt pyehr and mik-uh-lon',
      'An overseas collectivity of France in the North Atlantic Ocean.',
      'Saint Pierre and Miquelon is known for its French culture and history.',
      'The collectivity has a rich cultural heritage.',
      'Saint Pierre and Miquelon is the only remnant of the former French colonial empire in North America.'),
  CardData(
      'Pitcairn Islands',
      'pn.svg',
      'pit-kairn ahy-luhndz',
      'A British Overseas Territory in the Pacific Ocean.',
      'The Pitcairn Islands are known for their remoteness and history.',
      'The territory has a rich cultural heritage.',
      'The Pitcairn Islands are one of the most remote places in the world.'),
  CardData(
      'Puerto Rico',
      'pr.svg',
      'pwair-toh ree-koh',
      'A territory of the United States in the Caribbean.',
      'Puerto Rico is known for its beaches and culture.',
      'The territory has a rich cultural heritage.',
      'Puerto Rico is home to the only tropical rainforest in the U.S. National Forest System.'),
  CardData(
      'Palestine',
      'ps.svg',
      'pal-uh-stahyn',
      'A territory in the Middle East.',
      'Palestine is known for its history and culture.',
      'The territory has a rich cultural heritage.',
      'Palestine is home to many religious and historical sites.'),
  CardData(
      'Portugal',
      'pt.svg',
      'pohr-choo-guhl',
      'A country in Europe.',
      'Portugal is known for its history, culture, and coastline.',
      'The country has a rich cultural heritage.',
      'Portugal is one of the oldest countries in Europe.'),
  CardData(
      'Palau',
      'pw.svg',
      'puh-lou',
      'A country in the western Pacific Ocean.',
      'Palau is known for its marine life and coral reefs.',
      'The country has a rich cultural heritage.',
      'Palau is home to the Rock Islands, a UNESCO World Heritage Site.'),
  CardData(
      'Paraguay',
      'py.svg',
      'par-uh-gwahy',
      'A country in South America.',
      'Paraguay is known for its history and culture.',
      'The country has a rich cultural heritage.',
      'Paraguay is one of the two landlocked countries in South America.'),
  CardData(
      'Qatar',
      'qa.svg',
      'kah-tahr',
      'A country in the Middle East.',
      'Qatar is known for its wealth and modern architecture.',
      'The country has a rich cultural heritage.',
      'Qatar has the highest per capita income in the world.'),
  CardData(
      'Réunion',
      're.svg',
      'ray-yoo-nyon',
      'An overseas department of France in the Indian Ocean.',
      'Réunion is known for its volcanic activity and beaches.',
      'The department has a rich cultural heritage.',
      'Réunion is home to one of the most active volcanoes in the world, Piton de la Fournaise.'),
  CardData(
      'Romania',
      'ro.svg',
      'roh-mey-nee-uh',
      'A country in Europe.',
      'Romania is known for its history and castles.',
      'The country has a rich cultural heritage.',
      'Romania is home to the region of Transylvania, famous for its Dracula legend.'),
  CardData(
      'Russia',
      'ru.svg',
      'ruh-shuh',
      'A country in Eastern Europe and Northern Asia.',
      'Russia is known for its size and history.',
      'The country has a rich cultural heritage.',
      'Russia is the largest country in the world by land area.'),
  CardData(
      'Rwanda',
      'rw.svg',
      'roo-ahn-duh',
      'A country in East Africa.',
      'Rwanda is known for its wildlife and culture.',
      'The country has a rich cultural heritage.',
      'Rwanda is known as the "Land of a Thousand Hills."'),
  CardData(
      'Saudi Arabia',
      'sa.svg',
      'saw-dee uh-rey-bee-uh',
      'A country in the Middle East.',
      'Saudi Arabia is known for its deserts and oil wealth.',
      'The country has a rich cultural heritage.',
      'Saudi Arabia is home to Mecca, the holiest city in Islam.'),
  CardData(
      'Solomon Islands',
      'sb.svg',
      'sol-uh-muhn ahy-luhndz',
      'A country in the Pacific Ocean.',
      'The Solomon Islands are known for their beaches and World War II history.',
      'The country has a rich cultural heritage.',
      'The Solomon Islands are made up of over 900 islands.'),
  CardData(
      'Seychelles',
      'sc.svg',
      'sey-shelz',
      'A country in the Indian Ocean.',
      'Seychelles is known for its beaches and marine life.',
      'The country has a rich cultural heritage.',
      'Seychelles is one of the world\'s smallest countries by population.'),
  CardData(
      'Sudan',
      'sd.svg',
      'soo-dan',
      'A country in Northeast Africa.',
      'Sudan is known for its history and deserts.',
      'The country has a rich cultural heritage.',
      'Sudan is one of the largest countries in Africa by land area.'),
  CardData(
      'Sweden',
      'se.svg',
      'swee-duhn',
      'A country in Europe.',
      'Sweden is known for its natural beauty and high quality of life.',
      'The country has a rich cultural heritage.',
      'Sweden is one of the most prosperous countries in the world.'),
  CardData(
      'Singapore',
      'sg.svg',
      'sing-uh-pawr',
      'A city-state in Southeast Asia.',
      'Singapore is known for its modern architecture and cleanliness.',
      'The country has a rich cultural heritage.',
      'Singapore is one of the most densely populated countries in the world.'),
  CardData(
      'Saint Helena',
      'sh.svg',
      'seynt huh-lee-nuh',
      'A British Overseas Territory in the South Atlantic Ocean.',
      'Saint Helena is known for its remoteness and history.',
      'The territory has a rich cultural heritage.',
      'Saint Helena is where Napoleon Bonaparte was exiled.'),
  CardData(
      'Slovenia',
      'si.svg',
      'sloh-vee-nee-uh',
      'A country in Europe.',
      'Slovenia is known for its mountains and lakes.',
      'The country has a rich cultural heritage.',
      'Slovenia is one of the most forested countries in Europe.'),
  CardData(
      'Svalbard and Jan Mayen',
      'sj.svg',
      'svahl-bahrd and yahn may-uhn',
      'A Norwegian archipelago in the Arctic Ocean.',
      'Svalbard and Jan Mayen are known for their polar bears and Arctic environment.',
      'The archipelago has a unique cultural heritage.',
      'Svalbard is one of the world\'s northernmost inhabited areas.'),
  CardData(
      'Slovakia',
      'sk.svg',
      'sloh-vah-kee-uh',
      'A country in Europe.',
      'Slovakia is known for its castles and mountains.',
      'The country has a rich cultural heritage.',
      'Slovakia is home to many medieval castles.'),
  CardData(
      'Sierra Leone',
      'sl.svg',
      'see-air-uh lee-own',
      'A country in West Africa.',
      'Sierra Leone is known for its beaches and wildlife.',
      'The country has a rich cultural heritage.',
      'Sierra Leone is recovering from a devastating civil war.'),
  CardData(
      'San Marino',
      'sm.svg',
      'san muh-ree-noh',
      'A country in Europe.',
      'San Marino is known for its history and architecture.',
      'The country has a rich cultural heritage.',
      'San Marino is one of the oldest republics in the world.'),
  CardData(
      'Senegal',
      'sn.svg',
      'sen-uh-gawl',
      'A country in West Africa.',
      'Senegal is known for its music and culture.',
      'The country has a rich cultural heritage.',
      'Senegal is a major cultural hub in West Africa.'),
  CardData(
      'Somalia',
      'so.svg',
      'suh-mah-lee-uh',
      'A country in East Africa.',
      'Somalia is known for its culture and history.',
      'The country has a rich cultural heritage.',
      'Somalia is located in the Horn of Africa.'),
  CardData(
      'Suriname',
      'sr.svg',
      'soo-rih-nahm',
      'A country in South America.',
      'Suriname is known for its rainforests and diverse culture.',
      'The country has a rich cultural heritage.',
      'Suriname is the smallest country in South America by land area.'),
  CardData(
      'South Sudan',
      'ss.svg',
      'south soo-dan',
      'A country in East Africa.',
      'South Sudan is known for its culture and wildlife.',
      'The country has a rich cultural heritage.',
      'South Sudan is the newest country in the world, having gained independence in 2011.'),
  CardData(
      'São Tomé and Príncipe',
      'st.svg',
      'sow toh-mey and prin-si-pay',
      'A country in Central Africa.',
      'São Tomé and Príncipe is known for its beaches and biodiversity.',
      'The country has a rich cultural heritage.',
      'São Tomé and Príncipe is one of the smallest countries in Africa.'),
  CardData(
      'El Salvador',
      'sv.svg',
      'el sal-vuh-dawr',
      'A country in Central America.',
      'El Salvador is known for its beaches and volcanoes.',
      'The country has a rich cultural heritage.',
      'El Salvador is the smallest and most densely populated country in Central America.'),
  CardData(
      'Syria',
      'sy.svg',
      'seer-ee-uh',
      'A country in the Middle East.',
      'Syria is known for its history and culture.',
      'The country has a rich cultural heritage.',
      'Syria is home to some of the oldest continuously inhabited cities in the world.'),
  CardData(
      'Eswatini',
      'sz.svg',
      'ess-wah-tee-nee',
      'A country in Southern Africa.',
      'Eswatini is known for its culture and wildlife.',
      'The country has a rich cultural heritage.',
      'Eswatini is one of the smallest countries in Africa.'),
  CardData(
      'Turks and Caicos Islands',
      'tc.svg',
      'turks and kay-kohs ahy-luhndz',
      'A British Overseas Territory in the Caribbean.',
      'The Turks and Caicos Islands are known for their beaches and diving sites.',
      'The territory has a rich cultural heritage.',
      'The Turks and Caicos Islands are a popular tourist destination.'),
  CardData(
      'Chad',
      'td.svg',
      'chad',
      'A country in Central Africa.',
      'Chad is known for its deserts and wildlife.',
      'The country has a rich cultural heritage.',
      'Chad is home to Lake Chad, one of the largest lakes in Africa.'),
  CardData(
      'Togo',
      'tg.svg',
      'toh-goh',
      'A country in West Africa.',
      'Togo is known for its culture and traditions.',
      'The country has a rich cultural heritage.',
      'Togo is one of the smallest countries in Africa.'),
  CardData(
      'Thailand',
      'th.svg',
      'tahy-land',
      'A country in Southeast Asia.',
      'Thailand is known for its beaches, temples, and cuisine.',
      'The country has a rich cultural heritage.',
      'Thailand is the only Southeast Asian country never to have been colonized by a European power.'),
  CardData(
      'Tajikistan',
      'tj.svg',
      'tah-jik-uh-stan',
      'A country in Central Asia.',
      'Tajikistan is known for its mountains and culture.',
      'The country has a rich cultural heritage.',
      'Tajikistan is home to some of the highest mountains in the world.'),
  CardData(
      'Tokelau',
      'tk.svg',
      'toh-kuh-lou',
      'A territory of New Zealand in the South Pacific.',
      'Tokelau is known for its coral reefs and atolls.',
      'The territory has a rich cultural heritage.',
      'Tokelau is one of the most remote places in the world.'),
  CardData(
      'Timor-Leste',
      'tl.svg',
      'tee-mawr leh-stey',
      'A country in Southeast Asia.',
      'Timor-Leste is known for its beaches and mountains.',
      'The country has a rich cultural heritage.',
      'Timor-Leste is one of the newest countries in the world, having gained independence in 2002.'),
  CardData(
      'Turkmenistan',
      'tm.svg',
      'turk-men-uh-stan',
      'A country in Central Asia.',
      'Turkmenistan is known for its deserts and history.',
      'The country has a rich cultural heritage.',
      'Turkmenistan is home to the Karakum Desert, one of the largest deserts in the world.'),
  CardData(
      'Tunisia',
      'tn.svg',
      'too-nee-zhuh',
      'A country in North Africa.',
      'Tunisia is known for its history and culture.',
      'The country has a rich cultural heritage.',
      'Tunisia is home to the ancient city of Carthage.'),
  CardData(
      'Tonga',
      'to.svg',
      'tawng-guh',
      'A country in the South Pacific.',
      'Tonga is known for its islands and culture.',
      'The country has a rich cultural heritage.',
      'Tonga is the only Pacific nation never to have been colonized.'),
  CardData(
      'Turkey',
      'tr.svg',
      'tur-key',
      'A country in both Europe and Asia.',
      'Turkey is known for its history, culture, and cuisine.',
      'The country has a rich cultural heritage.',
      'Turkey is home to the city of Istanbul, a city that straddles two continents.'),
  CardData(
      'Trinidad and Tobago',
      'tt.svg',
      'trin-i-dad and tuh-bey-goh',
      'A country in the Caribbean.',
      'Trinidad and Tobago is known for its carnival and music.',
      'The country has a rich cultural heritage.',
      'Trinidad and Tobago is one of the wealthiest countries in the Caribbean.'),
  CardData(
      'Tuvalu',
      'tv.svg',
      'too-vah-loo',
      'A country in the Pacific Ocean.',
      'Tuvalu is known for its atolls and marine life.',
      'The country has a rich cultural heritage.',
      'Tuvalu is one of the smallest and least populous countries in the world.'),
  CardData(
      'Taiwan',
      'tw.svg',
      'tahy-wahn',
      'A territory in East Asia.',
      'Taiwan is known for its technology and culture.',
      'The territory has a rich cultural heritage.',
      'Taiwan is one of the most densely populated places in the world.'),
  CardData(
      'Tanzania',
      'tz.svg',
      'tan-zuh-nee-uh',
      'A country in East Africa.',
      'Tanzania is known for its wildlife and Mount Kilimanjaro.',
      'The country has a rich cultural heritage.',
      'Tanzania is home to the Serengeti National Park, famous for its annual wildebeest migration.'),
  CardData(
      'Ukraine',
      'ua.svg',
      'yoo-kreyn',
      'A country in Eastern Europe.',
      'Ukraine is known for its history and culture.',
      'The country has a rich cultural heritage.',
      'Ukraine is the largest country in Europe by land area.'),
  CardData(
      'Uganda',
      'ug.svg',
      'yoo-gan-duh',
      'A country in East Africa.',
      'Uganda is known for its wildlife and culture.',
      'The country has a rich cultural heritage.',
      'Uganda is home to Lake Victoria, the largest lake in Africa.'),
  CardData(
      'United States Minor Outlying Islands',
      'um.svg',
      'yoo-nahy-tid steyts mahy-ner out-lahy-ing ahy-luhndz',
      'A group of unincorporated territories of the United States.',
      'The United States Minor Outlying Islands are known for their remoteness and wildlife.',
      'The territories have a unique cultural heritage.',
      'The United States Minor Outlying Islands are scattered across the Pacific Ocean and the Caribbean Sea.'),
  CardData(
      'United States',
      'us.svg',
      'yoo-nahy-tid steyts',
      'A country in North America.',
      'The United States is known for its diversity and global influence.',
      'The country has a rich cultural heritage.',
      'The United States is one of the most culturally diverse countries in the world.'),
  CardData(
      'Uruguay',
      'uy.svg',
      'yoo-ruh-gwey',
      'A country in South America.',
      'Uruguay is known for its beaches and culture.',
      'The country has a rich cultural heritage.',
      'Uruguay is one of the most progressive countries in South America.'),
  CardData(
      'Uzbekistan',
      'uz.svg',
      'uhz-bek-uh-stan',
      'A country in Central Asia.',
      'Uzbekistan is known for its history and architecture.',
      'The country has a rich cultural heritage.',
      'Uzbekistan is home to many ancient cities, including Samarkand and Bukhara.'),
  CardData(
      'Vatican City',
      'va.svg',
      'vat-i-kuhn sit-ee',
      'A city-state surrounded by Rome, Italy.',
      'Vatican City is known for its religious and historical significance.',
      'The city-state has a rich cultural heritage.',
      'Vatican City is the smallest independent state in the world by both area and population.'),
  CardData(
      'Saint Vincent and the Grenadines',
      'vc.svg',
      'seynt vin-suhnt and the gren-uh-deenz',
      'A country in the Caribbean.',
      'Saint Vincent and the Grenadines is known for its islands and marine life.',
      'The country has a rich cultural heritage.',
      'Saint Vincent and the Grenadines is a popular tourist destination.'),
  CardData(
      'Venezuela',
      've.svg',
      'ven-uh-zway-luh',
      'A country in South America.',
      'Venezuela is known for its natural beauty and oil wealth.',
      'The country has a rich cultural heritage.',
      'Venezuela is home to Angel Falls, the world\'s highest waterfall.'),
  CardData(
      'British Virgin Islands',
      'vg.svg',
      'brit-ish vur-jin ahy-luhndz',
      'A British Overseas Territory in the Caribbean.',
      'The British Virgin Islands are known for their beaches and sailing.',
      'The territory has a rich cultural heritage.',
      'The British Virgin Islands are a popular destination for yacht charters.'),
  CardData(
      'United States Virgin Islands',
      'vi.svg',
      'yoo-nahy-tid steyts vur-jin ahy-luhndz',
      'A territory of the United States in the Caribbean.',
      'The United States Virgin Islands are known for their beaches and culture.',
      'The territory has a rich cultural heritage.',
      'The United States Virgin Islands are a popular tourist destination.'),
  CardData(
      'Vietnam',
      'vn.svg',
      'vee-et-nahm',
      'A country in Southeast Asia.',
      'Vietnam is known for its culture and cuisine.',
      'The country has a rich cultural heritage.',
      'Vietnam is one of the most densely populated countries in Southeast Asia.'),
  CardData(
      'Vanuatu',
      'vu.svg',
      'vah-noo-ah-too',
      'A country in the South Pacific.',
      'Vanuatu is known for its islands and culture.',
      'The country has a rich cultural heritage.',
      'Vanuatu is one of the most culturally diverse countries in the world.'),
  CardData(
      'Wallis and Futuna',
      'wf.svg',
      'wal-lis and fyoo-too-nuh',
      'A French overseas collectivity in the South Pacific.',
      'Wallis and Futuna is known for its culture and history.',
      'The collectivity has a rich cultural heritage.',
      'Wallis and Futuna is one of the most remote places in the world.'),
  CardData(
      'Samoa',
      'ws.svg',
      'suh-moh-uh',
      'A country in the South Pacific.',
      'Samoa is known for its culture and natural beauty.',
      'The country has a rich cultural heritage.',
      'Samoa is one of the most traditional countries in the South Pacific.'),
  CardData(
      'Yemen',
      'ye.svg',
      'ye-men',
      'A country in the Middle East.',
      'Yemen is known for its history and culture.',
      'The country has a rich cultural heritage.',
      'Yemen is home to many ancient cities and historical sites.'),
  CardData(
      'Mayotte',
      'yt.svg',
      'mah-yot',
      'A French overseas department in the Indian Ocean.',
      'Mayotte is known for its beaches and marine life.',
      'The department has a rich cultural heritage.',
      'Mayotte is home to one of the largest coral lagoons in the world.'),
  CardData(
      'South Africa',
      'za.svg',
      'south af-ri-kuh',
      'A country in Southern Africa.',
      'South Africa is known for its diversity and natural beauty.',
      'The country has a rich cultural heritage.',
      'South Africa is one of the most culturally diverse countries in the world.'),
  CardData(
      'Zambia',
      'zm.svg',
      'zam-bee-uh',
      'A country in Southern Africa.',
      'Zambia is known for its wildlife and Victoria Falls.',
      'The country has a rich cultural heritage.',
      'Zambia is home to one of the Seven Natural Wonders of the World, Victoria Falls.'),
  CardData(
      'Zimbabwe',
      'zw.svg',
      'zim-bah-bwee',
      'A country in Southern Africa.',
      'Zimbabwe is known for its history and wildlife.',
      'The country has a rich cultural heritage.',
      'Zimbabwe is home to the ruins of Great Zimbabwe, a medieval city.'),
];

class ExploreScreen extends StatefulWidget {
  const ExploreScreen({super.key});

  @override
  State<ExploreScreen> createState() => _ExploreScreenState();
}

class _ExploreScreenState extends State<ExploreScreen> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.topLeft,
      children: [
        Column(
          children: [
            Gap(context.mediaQueryPadding.top + 8),
            Row(
              children: [
                Gap(16.sw),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Explore Flags'.tr(),
                        style: w600TextStyle(fontSize: 18.sw),
                      ),
                      Gap(2.sw),
                      Text(
                        'List collection'.tr(),
                        style: w300TextStyle(fontSize: 12.sw),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            Gap(4.sw),
          ],
        ),
        cardList.isEmpty == true
            ? WidgetProblemLoading(
                callback: () {
                  appHaptic();
                },
              )
            : MasonryGridView.count(
                addAutomaticKeepAlives: false,
                padding: EdgeInsets.fromLTRB(
                    horizPadding,
                    12.sw + context.mediaQueryPadding.top + 50,
                    horizPadding,
                    12.sw),
                crossAxisCount: crossAxisCount,
                mainAxisSpacing: 8.sw,
                crossAxisSpacing: 8.sw,
                itemCount: cardList.length,
                itemBuilder: (context, index) {
                  return WidgetCardItem(
                    index: index,
                    data: cardList[index],
                  );
                },
              ),
      ],
    );
  }
}
