import 'package:internal_core/internal_core.dart';
import 'package:app/src/constants/constants.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:gap/gap.dart';

import '../home/widgets/widget_card_item.dart';
import '../widgets/widgets.dart';

var cardList = [
  CardData(
      "kayaking",
      "kayaking.png",
      "kay-ak-ing",
      "A sport or activity of paddling a kayak.",
      "Kayaking is popular in rivers.",
      "She loves kayaking during summer.",
      "Kayaking can be done on both calm and rough waters."),
  CardData(
      "bobsleigh",
      "bobsleigh.jpg",
      "bob-slay",
      "A winter sport in which teams make timed runs down narrow, twisting, banked ice tracks in a gravity-powered sled.",
      "Bobsleigh is a thrilling winter sport.",
      "The bobsleigh team practiced for hours.",
      "Bobsleigh originated in Switzerland."),
  CardData(
      "canoeing",
      "canoeing.png",
      "ca-noe-ing",
      "The activity of paddling a canoe.",
      "Canoeing is a popular recreational activity.",
      "We went canoeing on the lake.",
      "Canoeing dates back to prehistoric times."),
  CardData(
      "cross-country skiing",
      "cross-country skiing.gif",
      "cross-coun-try ski-ing",
      "A form of skiing where skiers rely on their own locomotion to move across snow-covered terrain.",
      "Cross-country skiing is great for endurance.",
      "He enjoys cross-country skiing in winter.",
      "It is also known as Nordic skiing."),
  CardData(
      "rafting",
      "rafting.png",
      "raft-ing",
      "A recreational outdoor activity which uses an inflatable raft to navigate a river or other bodies of water.",
      "Rafting is often done on whitewater.",
      "They went rafting down the Colorado River.",
      "Rafting can be dangerous in high water levels."),
  CardData(
      "skeleton",
      "skeleton.jpg",
      "skel-e-ton",
      "A winter sliding sport in which a person rides a small sled down a frozen track while lying face down.",
      "Skeleton is a high-speed sport.",
      "He competed in the skeleton race.",
      "Skeleton is considered the world's first sliding sport."),
  CardData(
      "snorkeling",
      "snorkeling.png",
      "snor-kel-ing",
      "The practice of swimming on or through a body of water while equipped with a diving mask, a shaped breathing tube called a snorkel, and usually swimfins.",
      "Snorkeling is great for observing underwater life.",
      "They went snorkeling in the coral reef.",
      "Snorkeling requires minimal equipment."),
  CardData(
      "olympic swimming",
      "olympic swimming.png",
      "o-lym-pic swim-ming",
      "Competitive swimming that takes place in the Olympic Games.",
      "Olympic swimming is a highly competitive sport.",
      "She won a gold medal in Olympic swimming.",
      "Michael Phelps is a famous Olympic swimmer."),
  CardData(
      "bodyboarding",
      "bodyboarding.png",
      "bod-y-board-ing",
      "A water sport in which the surfer rides a bodyboard on the crest, face, and curl of a wave.",
      "Bodyboarding is similar to surfing.",
      "They enjoyed bodyboarding at the beach.",
      "Bodyboarding is also known as boogie boarding."),
  CardData(
      "diving",
      "diving.png",
      "div-ing",
      "The sport or activity of jumping or falling into water from a platform or springboard.",
      "Diving can be performed at various heights.",
      "She practiced diving at the pool.",
      "Diving is an Olympic sport."),
  CardData(
      "freediving",
      "freediving.jpg",
      "free-div-ing",
      "A form of underwater diving that relies on the diver's ability to hold their breath until resurfacing rather than the use of a breathing apparatus.",
      "Freediving requires great breath control.",
      "He enjoys freediving in the ocean.",
      "Freediving is also known as apnea diving."),
  CardData(
      "paddle boarding",
      "paddle boarding.jpg",
      "pad-dle board-ing",
      "A water sport in which participants are propelled by a swimming motion using their arms while lying, kneeling, or standing on a paddleboard or surfboard in the ocean or other bodies of water.",
      "Paddle boarding is great for core strength.",
      "She loves paddle boarding on calm waters.",
      "Stand-up paddle boarding is a popular variation."),
  CardData(
      "rowing",
      "rowing.jpg",
      "row-ing",
      "The sport or activity of moving a boat by using oars.",
      "Rowing is an excellent full-body workout.",
      "They joined the rowing club at university.",
      "Rowing is one of the oldest Olympic sports."),
  CardData(
      "scuba diving",
      "scuba diving.jpg",
      "scu-ba div-ing",
      "A mode of underwater diving where the diver uses a self-contained underwater breathing apparatus (scuba) to breathe underwater.",
      "Scuba diving allows for deep underwater exploration.",
      "They went scuba diving in the Caribbean.",
      "Scuba stands for Self-Contained Underwater Breathing Apparatus."),
  CardData(
      "surfing",
      "surfing.jpg",
      "surf-ing",
      "A water sport in which the wave rider, referred to as a surfer, rides on the forward or deep face of a moving wave.",
      "Surfing is popular on coasts with strong waves.",
      "He learned surfing during his vacation.",
      "Hawaii is known as the birthplace of surfing."),
  CardData(
      "synchronized swimming",
      "synchronized swimming.png",
      "syn-chro-nized swim-ming",
      "A hybrid form of swimming, dance, and gymnastics, consisting of swimmers performing a synchronized routine of elaborate moves in the water, accompanied by music.",
      "Synchronized swimming requires precise timing.",
      "They performed synchronized swimming at the event.",
      "It is also known as artistic swimming."),
  CardData(
      "aerobics",
      "aerobics.png",
      "aer-o-bics",
      "A form of physical exercise that combines rhythmic aerobic exercise with stretching and strength training routines with the goal of improving all elements of fitness.",
      "Aerobics can be performed to music.",
      "She attends aerobics classes three times a week.",
      "Aerobics became popular in the 1980s."),
  CardData(
      "aikido",
      "aikido.jpg",
      "ai-ki-do",
      "A modern Japanese martial art developed by Morihei Ueshiba as a synthesis of his martial studies, philosophy, and religious beliefs.",
      "Aikido focuses on harmonizing with the opponent.",
      "He has been practicing aikido for years.",
      "Aikido means 'the way of harmony'."),
  CardData(
      "archery",
      "archery.jpg",
      "arch-er-y",
      "The sport or skill of shooting arrows with a bow.",
      "Archery requires great precision and control.",
      "They practiced archery at the range.",
      "Archery has been used for hunting and combat."),
  CardData(
      "artistic gymnastics",
      "artistic gymnastics.jpg",
      "ar-tis-tic gym-nast-ics",
      "A discipline of gymnastics in which athletes perform short routines on different apparatus, emphasizing strength, flexibility, balance, and coordination.",
      "Artistic gymnastics includes events like floor exercise and vault.",
      "She competed in artistic gymnastics at the Olympics.",
      "Nadia Comaneci is famous for her perfect 10 in gymnastics."),
  CardData(
      "baton twirling",
      "baton twirling.jpg",
      "ba-ton twirl-ing",
      "The skillful art of manipulating a metal rod and the performer’s body to a coordinated routine.",
      "Baton twirling often accompanies marching bands.",
      "She practiced baton twirling for the parade.",
      "Baton twirling requires agility and coordination."),
  CardData(
      "bodybuilding",
      "bodybuilding.jpg",
      "bod-y-build-ing",
      "The use of progressive resistance exercise to control and develop one’s musculature for aesthetic purposes.",
      "Bodybuilding focuses on muscle hypertrophy.",
      "He won the bodybuilding competition.",
      "Bodybuilding became popular with Arnold Schwarzenegger."),
  CardData(
      "boxing",
      "boxing.jpg",
      "box-ing",
      "A combat sport in which two people, usually wearing protective gloves, throw punches at each other for a predetermined amount of time in a boxing ring.",
      "Boxing is known for its rigorous training regimen.",
      "He has been training in boxing for years.",
      "Muhammad Ali is a legendary boxer."),
  CardData(
      "cross-country riding",
      "cross-country riding.png",
      "cross-coun-try rid-ing",
      "An equestrian sport where horses and riders are required to jump over a variety of obstacles on a long outdoor course.",
      "Cross-country riding tests endurance and skill.",
      "They participated in cross-country riding events.",
      "It is part of the equestrian triathlon."),
  CardData(
      "cross-country running",
      "cross-country running.png",
      "cross-coun-try run-ning",
      "A sport in which teams and individuals run a race on open-air courses over natural terrain.",
      "Cross-country running is held in the fall or winter.",
      "She enjoys cross-country running in the countryside.",
      "It requires great stamina and endurance."),
  CardData(
      "cycling",
      "cycling.png",
      "cyc-ling",
      "The use of bicycles for transport, recreation, exercise, or sport.",
      "Cycling is a low-impact exercise.",
      "They went cycling through the city.",
      "The Tour de France is a famous cycling race."),
  CardData(
      "discus throw",
      "discus throw.png",
      "dis-cus throw",
      "An event in athletics in which a heavy disc is thrown as far as possible.",
      "The discus throw is a classic track and field event.",
      "He set a new record in the discus throw.",
      "It has been part of the Olympics since ancient times."),
  CardData(
      "fencing",
      "fencing.png",
      "fenc-ing",
      "A sport in which two competitors fight using 'rapier-style' swords, winning points by making contact with their opponent.",
      "Fencing is known as a 'game of physical chess'.",
      "She competed in fencing tournaments.",
      "There are three types of fencing swords: foil, épée, and sabre."),
  CardData(
      "figure skating",
      "figure skating.png",
      "fig-ure skat-ing",
      "A sport in which individuals, duos, or groups perform on figure skates on ice.",
      "Figure skating combines athleticism and artistry.",
      "They watched the figure skating competition.",
      "It includes events like singles, pairs, and ice dance."),
  CardData(
      "horseback riding",
      "horseback riding.png",
      "horse-back rid-ing",
      "The skill of riding, driving, steeplechasing, or vaulting with horses.",
      "Horseback riding is enjoyed by people of all ages.",
      "She takes horseback riding lessons.",
      "It can be both a recreational activity and a competitive sport."),
  CardData(
      "horse racing",
      "horse racing.png",
      "horse rac-ing",
      "An equestrian performance sport, typically involving two or more horses ridden by jockeys over a set distance for competition.",
      "Horse racing is known as 'The Sport of Kings'.",
      "They attended the horse racing event.",
      "The Kentucky Derby is a famous horse race."),
  CardData(
      "judo",
      "judo.png",
      "ju-do",
      "A modern martial art, combat, and Olympic sport created in Japan.",
      "Judo emphasizes throws and ground fighting.",
      "He earned a black belt in judo.",
      "It was founded by Jigoro Kano in 1882."),
  CardData(
      "karate",
      "karate.png",
      "ka-ra-te",
      "A martial art developed in the Ryukyu Kingdom, involving punching, kicking, knee strikes, elbow strikes, and open-hand techniques.",
      "Karate focuses on self-defense and discipline.",
      "She practices karate every day.",
      "Karate is now an Olympic sport."),
  CardData(
      "kendo",
      "kendo.png",
      "ken-do",
      "A modern Japanese martial art, which descended from swordsmanship and uses bamboo swords and protective armor.",
      "Kendo means 'the way of the sword'.",
      "He trains in kendo at the dojo.",
      "Kendo emphasizes discipline and respect."),
  CardData(
      "kickboxing",
      "kickboxing.png",
      "kick-box-ing",
      "A group of stand-up combat sports based on kicking and punching, historically developed from karate mixed with boxing.",
      "Kickboxing is great for fitness and self-defense.",
      "She joined a kickboxing class.",
      "It is also used in mixed martial arts."),
  CardData(
      "kung fu",
      "kung fu.png",
      "kung fu",
      "A Chinese martial art that includes a number of fighting styles developed over centuries.",
      "Kung fu focuses on flexibility and speed.",
      "He has been learning kung fu for years.",
      "It is also known as Wushu."),
  CardData(
      "long jump",
      "long jump.png",
      "long jump",
      "An athletic (track and field) event in which athletes combine speed, strength, and agility in an attempt to leap as far as possible from a take-off point.",
      "Long jump requires both speed and power.",
      "He broke the school record in long jump.",
      "It has been part of the Olympic Games since 1896."),
  CardData(
      "marathon",
      "marathon.png",
      "mar-a-thon",
      "A long-distance running race with an official distance of 42.195 kilometers (26.219 miles).",
      "Running a marathon is a significant achievement.",
      "She trained for months to run the marathon.",
      "The first marathon was inspired by the run of a Greek soldier."),
  CardData(
      "mixed martial arts",
      "mixed martial arts.png",
      "mixed mar-tial arts",
      "A full-contact combat sport that allows a wide variety of fighting techniques and skills from a mixture of other combat sports.",
      "Mixed martial arts includes techniques from various disciplines.",
      "He is a professional mixed martial arts fighter.",
      "The UFC is a major mixed martial arts organization."),
  CardData(
      "Muay Thai",
      "Muay Thai.png",
      "muay thai",
      "A combat sport of Thailand that uses stand-up striking along with various clinching techniques.",
      "Muay Thai is known as the 'art of eight limbs'.",
      "She trains in Muay Thai every week.",
      "It is Thailand's national sport."),
  CardData(
      "pole vault",
      "pole vault.png",
      "pole vault",
      "An event in which an athlete uses a long, flexible pole as an aid to jump over a bar.",
      "Pole vault requires speed, strength, and technique.",
      "He cleared the bar in the pole vault competition.",
      "It has been part of the Olympic Games since 1896."),
  CardData(
      "powerlifting",
      "powerlifting.png",
      "pow-er-lift-ing",
      "A strength sport that consists of three attempts at maximal weight on three lifts: squat, bench press, and deadlift.",
      "Powerlifting focuses on maximum strength.",
      "She competed in a powerlifting meet.",
      "Powerlifting is different from Olympic weightlifting."),
  CardData(
      "racewalking",
      "racewalking.png",
      "race-walk-ing",
      "A long-distance discipline within the sport of athletics. Although it is a foot race, it is different from running in that one foot must appear to be in contact with the ground at all times.",
      "Racewalking is an Olympic event.",
      "He trained for the racewalking competition.",
      "It requires a unique walking technique."),
  CardData(
      "rhythmic gymnastics",
      "rhythmic gymnastics.png",
      "rhyth-mic gym-nast-ics",
      "A sport in which individuals or teams of five manipulate one or two pieces of apparatus: rope, hoop, ball, clubs, and ribbon.",
      "Rhythmic gymnastics combines elements of ballet, gymnastics, dance, and apparatus manipulation.",
      "She practices rhythmic gymnastics with a ribbon.",
      "It became an Olympic sport in 1984."),
  CardData(
      "sprint",
      "sprint.png",
      "sprint",
      "Running over a short distance in a limited period of time.",
      "Sprinting requires explosive power and speed.",
      "He participated in the 100m sprint.",
      "Usain Bolt is famous for his sprinting records."),
  CardData(
      "sumo",
      "sumo.png",
      "su-mo",
      "A competitive full-contact wrestling sport where a wrestler attempts to force another wrestler out of a circular ring or to touch the ground with anything other than the soles of their feet.",
      "Sumo is a traditional Japanese sport.",
      "He watched a sumo wrestling match.",
      "Sumo wrestlers are called rikishi."),
  CardData(
      "sword-fighting",
      "sword-fighting.png",
      "sword-fight-ing",
      "The act of fighting with swords.",
      "Sword-fighting requires skill and agility.",
      "They practiced sword-fighting techniques.",
      "It is often seen in historical and fantasy contexts."),
  CardData(
      "trail running",
      "trail running.png",
      "trail run-ning",
      "The sport of running and hiking over trails.",
      "Trail running offers challenging and scenic routes.",
      "She loves trail running in the mountains.",
      "It differs from road running due to the varied terrain."),
  CardData(
      "trampolining",
      "trampolining.png",
      "tram-po-lin-ing",
      "A sport in which athletes perform acrobatics while bouncing on a trampoline.",
      "Trampolining requires coordination and balance.",
      "He practiced trampolining at the gym.",
      "It became an Olympic sport in 2000."),
  CardData(
      "tumbling",
      "tumbling.gif",
      "tum-bling",
      "The gymnastic and acrobatic sport of performing various leaps, somersaults, and other acrobatic feats.",
      "Tumbling involves performing flips and twists.",
      "She excels in tumbling routines.",
      "It is often seen in cheerleading and gymnastics."),
  CardData(
      "ultimate frisbee",
      "ultimate frisbee.png",
      "ul-ti-mate fris-bee",
      "A non-contact team sport played with a flying disc (frisbee).",
      "Ultimate frisbee combines elements of soccer and football.",
      "They played ultimate frisbee at the park.",
      "It is known for its emphasis on sportsmanship."),
  CardData(
      "walking",
      "walking.png",
      "walk-ing",
      "The act of traveling on foot at a moderate pace.",
      "Walking is a great form of low-impact exercise.",
      "She enjoys walking in the evenings.",
      "It is one of the easiest ways to stay active."),
  CardData(
      "weightlifting",
      "weightlifting.png",
      "weight-lift-ing",
      "A sport in which athletes attempt a maximum-weight single lift of a barbell loaded with weight plates.",
      "Weightlifting includes the snatch and clean and jerk.",
      "He broke the national record in weightlifting.",
      "It is an Olympic sport with a long history."),
  CardData(
      "wrestling",
      "wrestling.png",
      "wres-tling",
      "A sport in which two competitors attempt to throw or immobilize each other by grappling.",
      "Wrestling is one of the oldest forms of combat.",
      "He competed in the wrestling tournament.",
      "It is included in the modern Olympic Games."),
  CardData(
      "baseball",
      "baseball.png",
      "base-ball",
      "A bat-and-ball game played between two teams who take turns batting and fielding.",
      "Baseball is known as America's pastime.",
      "They watched a baseball game at the stadium.",
      "The World Series is the championship series of Major League Baseball."),
  CardData(
      "basketball",
      "basketball.png",
      "bas-ket-ball",
      "A team sport in which two teams, most commonly of five players each, opposing one another on a rectangular court, compete with the primary objective of shooting a basketball through the defender's hoop.",
      "Basketball requires agility and teamwork.",
      "He plays basketball with his friends every weekend.",
      "The NBA is the premier basketball league in the world."),
  CardData(
      "tennis",
      "tennis.png",
      "ten-nis",
      "A racket sport that can be played individually against a single opponent or between two teams of two players each.",
      "Tennis is played on a rectangular court.",
      "She has been taking tennis lessons.",
      "Wimbledon is the oldest tennis tournament in the world."),
  CardData(
      "badminton",
      "badminton.png",
      "bad-min-ton",
      "A racquet sport played using racquets to hit a shuttlecock across a net.",
      "Badminton is played indoors or outdoors.",
      "They played badminton in the backyard.",
      "The shuttlecock is also known as a birdie."),
  CardData(
      "bowling",
      "bowling.png",
      "bowl-ing",
      "A sport or leisure activity in which a player rolls or throws a bowling ball towards pins.",
      "Bowling is a popular recreational activity.",
      "He went bowling with friends.",
      "A perfect game in bowling is a score of 300."),
  CardData(
      "cricket",
      "cricket.png",
      "crick-et",
      "A bat-and-ball game played between two teams of eleven players on a field at the center of which is a 22-yard pitch with a wicket at each end.",
      "Cricket is popular in many countries.",
      "They watched a cricket match.",
      "The Ashes is a famous cricket series between England and Australia."),
  CardData(
      "curling",
      "curling.png",
      "curl-ing",
      "A sport in which players slide stones on a sheet of ice towards a target area segmented into four concentric circles.",
      "Curling is known as 'chess on ice'.",
      "They enjoyed watching curling during the Winter Olympics.",
      "The sport originated in Scotland."),
  CardData(
      "dodgeball",
      "dodgeball.png",
      "dodge-ball",
      "A team sport in which players on two teams try to throw balls and hit opponents while avoiding being hit themselves.",
      "Dodgeball is played in schools and recreational leagues.",
      "They played dodgeball at the gym.",
      "The goal is to eliminate all players on the opposing team."),
  CardData(
      "football",
      "football.png",
      "foot-ball",
      "A family of team sports that involve, to varying degrees, kicking a ball to score a goal.",
      "Football is known as soccer in some countries.",
      "They watched the football match at the stadium.",
      "The FIFA World Cup is the biggest football tournament."),
  // Thêm các môn thể thao còn lại theo mẫu tương tự
];

class ExploreScreen extends StatefulWidget {
  const ExploreScreen({super.key});

  @override
  State<ExploreScreen> createState() => _ExploreScreenState();
}

class _ExploreScreenState extends State<ExploreScreen> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.topLeft,
      children: [
        Column(
          children: [
            Gap(context.mediaQueryPadding.top + 8),
            Row(
              children: [
                Gap(16.sw),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Explore Sports'.tr(),
                        style: w600TextStyle(fontSize: 18.sw),
                      ),
                      Gap(2.sw),
                      Text(
                        'List collection'.tr(),
                        style: w300TextStyle(fontSize: 12.sw),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            Gap(4.sw),
          ],
        ),
        cardList.isEmpty == true
            ? WidgetProblemLoading(
                callback: () {
                  appHaptic();
                },
              )
            : MasonryGridView.count(
                addAutomaticKeepAlives: false,
                padding: EdgeInsets.fromLTRB(
                    horizPadding,
                    12.sw + context.mediaQueryPadding.top + 50,
                    horizPadding,
                    12.sw),
                crossAxisCount: crossAxisCount,
                mainAxisSpacing: 8.sw,
                crossAxisSpacing: 8.sw,
                itemCount: cardList.length,
                itemBuilder: (context, index) {
                  return WidgetCardItem(
                    index: index,
                    data: cardList[index],
                  );
                },
              ),
      ],
    );
  }
}
