// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCixX_R6yIqmhu0-O6xoL5pj8MErNg23f0',
    appId: '1:319437602723:android:4302a6bb3ec7a53687a416',
    messagingSenderId: '319437602723',
    projectId: 'trash-apps-fa408',
    storageBucket: 'trash-apps-fa408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxPD3bf-3x2qRBsXbHH0G0qoOSv_R4skU',
    appId: '1:319437602723:ios:c8c994ebc8906efd87a416',
    messagingSenderId: '319437602723',
    projectId: 'trash-apps-fa408',
    storageBucket: 'trash-apps-fa408.appspot.com',
    iosBundleId: 'com.mminhlequang.pictalkflags',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxPD3bf-3x2qRBsXbHH0G0qoOSv_R4skU',
    appId: '1:319437602723:ios:c8c994ebc8906efd87a416',
    messagingSenderId: '319437602723',
    projectId: 'trash-apps-fa408',
    storageBucket: 'trash-apps-fa408.appspot.com',
    iosBundleId: 'com.mminhlequang.pictalkflags',
  );
}
