# Copyright (c) 2022, Md. Siam
# http://mdsiam.xyz/
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://choosealicense.com/licenses/mit/
name: flutter_puzzle_hack
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # For awesome icons
  font_awesome_flutter: ^10.7.0
  # For accessing google fonts
  google_fonts: ^6.2.1
  # For responsive UI
  responsive_framework: ^1.4.0
  ## For responsive SizedBox
  responsive_sizer: ^3.3.1
  # For state-management
  provider: ^6.1.2
  # For modern neumorphic containers
  clay_containers: ^0.3.4
  # For animated switch to activate dark/light mode
  day_night_switcher: ^0.2.0+1
  audioplayers: ^6.0.0
  
  internal_core: 
    path: ../internal_libs/core


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0


flutter_icons:
  android: "ic_launcher"
  ios: true
  #ios
  image_path: "assets/logo.png"
  #android 
  adaptive_icon_foreground: "assets/logo2.png"
  adaptive_icon_background: "#F2F2F2"
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter_native_splash:
  color: "#F1FCFF"
  image: assets/logo2.png
  web: false
  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/icons/
    - assets/lotties/
